// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuD9q81xLs_Rp_GJcVhIYh0Ky86AuzvA',
    appId: '1:761105631689:web:504f0841659ecd86a34018',
    messagingSenderId: '761105631689',
    projectId: 'bomberman-1cbdc',
    authDomain: 'bomberman-1cbdc.firebaseapp.com',
    storageBucket: 'bomberman-1cbdc.firebasestorage.app',
    measurementId: 'G-NQGRWJQLLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9n8HYgNxP24vzyKwZbXj12n7yNRKiao',
    appId: '1:761105631689:android:01d42fe4616cf9a2a34018',
    messagingSenderId: '761105631689',
    projectId: 'bomberman-1cbdc',
    storageBucket: 'bomberman-1cbdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs25v_LMi-v2KTqEnKY-eZckDTAnWuFac',
    appId: '1:761105631689:ios:7321178d62f7c42ea34018',
    messagingSenderId: '761105631689',
    projectId: 'bomberman-1cbdc',
    storageBucket: 'bomberman-1cbdc.firebasestorage.app',
    iosBundleId: 'com.example.bomberman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs25v_LMi-v2KTqEnKY-eZckDTAnWuFac',
    appId: '1:761105631689:ios:7321178d62f7c42ea34018',
    messagingSenderId: '761105631689',
    projectId: 'bomberman-1cbdc',
    storageBucket: 'bomberman-1cbdc.firebasestorage.app',
    iosBundleId: 'com.example.bomberman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmuD9q81xLs_Rp_GJcVhIYh0Ky86AuzvA',
    appId: '1:761105631689:web:85a97f01a987c7c1a34018',
    messagingSenderId: '761105631689',
    projectId: 'bomberman-1cbdc',
    authDomain: 'bomberman-1cbdc.firebaseapp.com',
    storageBucket: 'bomberman-1cbdc.firebasestorage.app',
    measurementId: 'G-G6RLRHF6QK',
  );
}
